---
- name: Check && install python
  hosts: all
  become: true
  gather_facts: False

  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D68FA50FEA312927 || (apt -y update && apt install -y python-minimal)
      changed_when: False
